# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/keajacm/Documents/repositories/CPU_8b/nexys_core/CPU_8b/CPU_8b.srcs/sources_1/ip/GPR/GPR.xci
# IP: The module: 'GPR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keajacm/Documents/repositories/CPU_8b/nexys_core/CPU_8b/CPU_8b.gen/sources_1/ip/GPR/GPR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPR'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/keajacm/Documents/repositories/CPU_8b/nexys_core/CPU_8b/CPU_8b.srcs/sources_1/ip/GPR/GPR.xci
# IP: The module: 'GPR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keajacm/Documents/repositories/CPU_8b/nexys_core/CPU_8b/CPU_8b.gen/sources_1/ip/GPR/GPR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPR'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
